# File: update_init.py
import os

TARGET_DIR = "src/nuvai"
INIT_FILE = os.path.join(TARGET_DIR, "__init__.py")
EXCLUDE_FILES = {"__init__.py", "__pycache__"}
modules = [
    f[:-3] for f in os.listdir(TARGET_DIR)
    if f.endswith(".py") and f not in EXCLUDE_FILES
]

import_lines = [f"from .{m} import *" for m in modules]
content = (
    '"""\n'
    'This file is auto-generated by update_init.py\n'
    'Do not edit manually.\n'
    '"""\n\n'
    + "\n".join(import_lines)
    + "\n\n__all__ = [\n"
    + ",\n".join([f'    \"{m}\"' for m in modules])
    + "\n]"
)

with open(INIT_FILE, "w") as f:
    f.write(content)