"""
File: update_init.py

Description:
This utility script automatically updates the __init__.py file inside the
src/nuvai/ directory. It scans all Python files in the directory, and generates
import statements and an __all__ list so that Nuvai core modules can be easily imported.

Usage:
Run this script manually whenever you add or remove files in src/nuvai/

Example:
$ python3 update_init.py
"""

import os

TARGET_DIR = "src/nuvai"
INIT_FILE = os.path.join(TARGET_DIR, "__init__.py")

# Files to ignore
EXCLUDE_FILES = {"__init__.py", "__pycache__"}

# Collect module names
modules = [
    f[:-3] for f in os.listdir(TARGET_DIR)
    if f.endswith(".py") and f not in EXCLUDE_FILES
]

# Build import lines
import_lines = [f"from .{m} import *" for m in modules]

# Construct full content with better formatting
content = (
    '"""\n'
    'This file is auto-generated by update_init.py\n'
    'Do not edit manually.\n'
    '"""\n\n'
    + "\n".join(import_lines)
    + "\n\n__all__ = [\n"
    + ",\n".join([f'    \"{m}\"' for m in modules])
    + "\n]"
)

# Write to __init__.py
with open(INIT_FILE, "w") as f:
    f.write(content)

print(f"✅ {INIT_FILE} updated with {len(modules)} modules.")